### ISSUE TITLE
Error arises when some variables do not vary across rows.

### ISSUE THREAD

**Issue by estacy** [kosukeimai/FindIt#10]
Hi, I'm using the FindIt package to find important areas of heterogeneity and found that I received the below error.

"Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 7212"

After much troubleshooting I found that it was due to having a few columns that were all zeros or all 1's. This is obviously not something I want to include in my formula, but it was hard to find the culprit based on this error, and it may have been useful if the function could still run but just drop/omit those vars and print a message letting me know which were dropped, since I have a few hundred variables and it took digging to find out what was wrong. 

As a sidenote, I wish that I was able to give the formula a vector of variable names rather than having to paste them all in, in a case like mine with several hundred variables included. I was able to write code to paste them all out for me collapsed by + signs but it could be useful given that this FindIt function is well suited to situations with many variables. 

Very useful package, thank you!!

**Comment by estacy** [comment]
I will try this and let you know. I have been running the function for over an hour and it still has not printed anything, I believe due to the large number of variables. 

In order to speed up the calculation, is there a way to specify that only **treat:covariate** interactions be calculated, rather than all combinations of **treat:covariate1:covariate2:covariate3**...etc. ?

**Comment by naoki-egami** [comment]
FindIt takes the argument, "model.int", in which you can specify covariate to be interacted with the main treatment variable.
