### ISSUE TITLE
Nested Data, Repeated Observations

### ISSUE THREAD

**Issue by shakty** [kosukeimai/FindIt#11]
Hi,

thanks for creating this great package! I have a question/comment. 

I wonder if/how this procedure is applicable to nested data and repeated observations from same individuals. Imai and Ratkovic (2013) assume "no interference among units," and say that this is standard in randomized experiments. However, in group-behavior experiments this is rather non-standard. In fact, the same group of individuals interact for multiple rounds. My first attempt has been to average each participant's response and run FindIt on this averaged dataset. However, this approach is clearly not satisfactory because it does not make use of all information, and it does not take into account of in-group correlations. In the rest of my analysis, I use the lme4 package to model the structure individual+group. Is there a way to apply LASSO to lmer? What is the recommended approach?

Thanks!

**Comment by naoki-egami** [comment]
Thanks for the question. The package is not designed for analyzing experiments when there is some in-group interference/interaction. When there is interference between units and you want to explicitly take it into account, it might be good to employ methods from the literature of interference, such as Hudgens and Halloran (2008).
