### ISSUE TITLE
plot.PredictFindIt with locator is confusing

### ISSUE THREAD

**Issue by HeidiSeibold** [kosukeimai/FindIt#8]
It is very unusal that a plot function uses `identify()`. I feel like it would be more user-friendly to have this as an option but not as the default.

I am a frequent R user and have never seen a behaviour like this in a plot. It took me a while to figure out what had happened when the R code was stuck.

**Comment by naoki-egami** [comment]
Thanks for letting us know. An interactive plot is now an option rather than the default!
